name: "Set up env"
description: "Install binaries and log in to required to registries for buildpack and result images"

inputs:
  buildpack-registry:
    required: true
  image-registry:
    required: true
  jfrog-username:
    required: true
  jfrog-image-password:
    required: true
  jfrog-buildpack-password:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install pack cli
      shell: bash
      run: |
        curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.38.2/pack-v0.38.2-linux.tgz" \
        | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack
      
    - name: Log in to buildpack registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.buildpack-registry }}
        username: ${{ inputs.jfrog-username }}
        password: ${{ inputs.jfrog-buildpack-password }}

    - name: Log in to container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.image-registry}}
        username: ${{ inputs.jfrog-username }}
        password: ${{ inputs.jfrog-image-password }}